In [19]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline
import seaborn as sns
from sklearn import metrics
import warnings
warnings.filterwarnings('ignore')

In [20]:

import os, types
import pandas as pd
from botocore.client import Config
import ibm_boto3

def __iter__(self): return 0

# @hidden_cell
# The following code accesses a file in your IBM Cloud Object Storage. It includes your credentials.
# You might want to remove those credentials before you share the notebook.
cos_client = ibm_boto3.client(service_name='s3',
    ibm_api_key_id='5R73qcy0t4mnMYG7VBnYKT8VLbRAXd0eOjK0enP7iwFz',
    ibm_auth_endpoint="https://iam.cloud.ibm.com/oidc/token",
    config=Config(signature_version='oauth'),
    endpoint_url='https://s3.private.us.cloud-object-storage.appdomain.cloud')

bucket = 'webphishingdetection-donotdelete-pr-fwpuuyxh90dcqj'
object_key = 'dataset_website.csv'

body = cos_client.get_object(Bucket=bucket,Key=object_key)['Body']
# add missing __iter__ method, so pandas accepts body as file-like object
if not hasattr(body, "__iter__"): body.__iter__ = types.MethodType( __iter__, body )

data = pd.read_csv(body)
data.head()


index  having_IPhaving_IP_Address  URLURL_Length  Shortining_Service  \
0      1                          -1              1                   1   
1      2                           1              1                   1   
2      3                           1              0                   1   
3      4                           1              0                   1   
4      5                           1              0                  -1   

   having_At_Symbol  double_slash_redirecting  Prefix_Suffix  \
0                 1                        -1             -1   
1                 1                         1             -1   
2                 1                         1             -1   
3                 1                         1             -1   
4                 1                         1             -1   

   having_Sub_Domain  SSLfinal_State  Domain_registeration_length  ...  \
0                 -1              -1                           -1  ...   
1                  0               1                           -1  ...   
2                 -1              -1                           -1  ...   
3                 -1              -1                            1  ...   
4                  1               1                           -1  ...   

   popUpWidnow  Iframe  age_of_domain  DNSRecord  web_traffic  Page_Rank  \
0            1       1             -1         -1           -1         -1   
1            1       1             -1         -1            0         -1   
2            1       1              1         -1            1         -1   
3            1       1             -1         -1            1         -1   
4           -1       1             -1         -1            0         -1   

   Google_Index  Links_pointing_to_page  Statistical_report  Result  
0             1                       1                  -1      -1  
1             1                       1                   1      -1  
2             1                       0                  -1      -1  
3             1                      -1                   1      -1  
4             1                       1                   1       1  

[5 rows x 32 columns]

In [21]:
type(data)

pandas.core.frame.DataFrame

In [22]:
data_main=pd.get_dummies(data,columns=['Prefix_Suffix'])
data_main

index  having_IPhaving_IP_Address  URLURL_Length  Shortining_Service  \
0          1                          -1              1                   1   
1          2                           1              1                   1   
2          3                           1              0                   1   
3          4                           1              0                   1   
4          5                           1              0                  -1   
...      ...                         ...            ...                 ...   
11050  11051                           1             -1                   1   
11051  11052                          -1              1                   1   
11052  11053                           1             -1                   1   
11053  11054                          -1             -1                   1   
11054  11055                          -1             -1                   1   

       having_At_Symbol  double_slash_redirecting  having_Sub_Domain  \
0                     1                        -1                 -1   
1                     1                         1                  0   
2                     1                         1                 -1   
3                     1                         1                 -1   
4                     1                         1                  1   
...                 ...                       ...                ...   
11050                -1                         1                  1   
11051                -1                        -1                  1   
11052                 1                         1                  1   
11053                 1                         1                 -1   
11054                 1                         1                 -1   

       SSLfinal_State  Domain_registeration_length  Favicon  ...  \
0                  -1                           -1        1  ...   
1                   1                           -1        1  ...   
2                  -1                           -1        1  ...   
3                  -1                            1        1  ...   
4                   1                           -1        1  ...   
...               ...                          ...      ...  ...   
11050               1                           -1       -1  ...   
11051              -1                           -1       -1  ...   
11052              -1                           -1        1  ...   
11053              -1                            1       -1  ...   
11054              -1                            1        1  ...   

       age_of_domain  DNSRecord  web_traffic  Page_Rank  Google_Index  \
0                 -1         -1           -1         -1             1   
1                 -1         -1            0         -1             1   
2                  1         -1            1         -1             1   
3                 -1         -1            1         -1             1   
4                 -1         -1            0         -1             1   
...              ...        ...          ...        ...           ...   
11050              1          1           -1         -1             1   
11051              1          1            1          1             1   
11052              1          1            1         -1             1   
11053              1          1            1         -1             1   
11054             -1          1           -1         -1            -1   

       Links_pointing_to_page  Statistical_report  Result  Prefix_Suffix_-1  \
0                           1                  -1      -1                 1   
1                           1                   1      -1                 1   
2                           0                  -1      -1                 1   
3                          -1                   1      -1                 1   
4                           1                   1       1                 1   
...                      

In [23]:

import os, types
import pandas as pd
from botocore.client import Config
import ibm_boto3

def __iter__(self): return 0

# @hidden_cell
# The following code accesses a file in your IBM Cloud Object Storage. It includes your credentials.
# You might want to remove those credentials before you share the notebook.
cos_client = ibm_boto3.client(service_name='s3',
    ibm_api_key_id='5R73qcy0t4mnMYG7VBnYKT8VLbRAXd0eOjK0enP7iwFz',
    ibm_auth_endpoint="https://iam.cloud.ibm.com/oidc/token",
    config=Config(signature_version='oauth'),
    endpoint_url='https://s3.private.us.cloud-object-storage.appdomain.cloud')

bucket = 'webphishingdetection-donotdelete-pr-fwpuuyxh90dcqj'
object_key = 'dataset_website.csv'

body = cos_client.get_object(Bucket=bucket,Key=object_key)['Body']
# add missing __iter__ method, so pandas accepts body as file-like object
if not hasattr(body, "__iter__"): body.__iter__ = types.MethodType( __iter__, body )

df_data_1 = pd.read_csv(body)
df_data_1.head()
y=data_main['URLURL_Length']
y.head()

0    1
1    1
2    0
3    0
4    0
Name: URLURL_Length, dtype: int64

In [24]:
x=data_main.drop(columns=['URLURL_Length'],axis=1)
x.head()

index  having_IPhaving_IP_Address  Shortining_Service  having_At_Symbol  \
0      1                          -1                   1                 1   
1      2                           1                   1                 1   
2      3                           1                   1                 1   
3      4                           1                   1                 1   
4      5                           1                  -1                 1   

   double_slash_redirecting  having_Sub_Domain  SSLfinal_State  \
0                        -1                 -1              -1   
1                         1                  0               1   
2                         1                 -1              -1   
3                         1                 -1              -1   
4                         1                  1               1   

   Domain_registeration_length  Favicon  port  ...  age_of_domain  DNSRecord  \
0                           -1        1     1  ...             -1         -1   
1                           -1        1     1  ...             -1         -1   
2                           -1        1     1  ...              1         -1   
3                            1        1     1  ...             -1         -1   
4                           -1        1     1  ...             -1         -1   

   web_traffic  Page_Rank  Google_Index  Links_pointing_to_page  \
0           -1         -1             1                       1   
1            0         -1             1                       1   
2            1         -1             1                       0   
3            1         -1             1                      -1   
4            0         -1             1                       1   

   Statistical_report  Result  Prefix_Suffix_-1  Prefix_Suffix_1  
0                  -1      -1                 1                0  
1                   1      -1                 1                0  
2                  -1      -1                 1                0  
3                   1      -1                 1                0  
4                   1       1                 1                0  

[5 rows x 32 columns]

In [25]:
from sklearn.model_selection import train_test_split

In [26]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=0)

In [27]:
x_train

index  having_IPhaving_IP_Address  Shortining_Service  \
5033    5034                           1                   1   
10307  10308                           1                   1   
7563    7564                          -1                   1   
5911    5912                           1                   1   
9823    9824                           1                   1   
...      ...                         ...                 ...   
4859    4860                           1                   1   
3264    3265                           1                   1   
9845    9846                          -1                   1   
10799  10800                          -1                   1   
2732    2733                           1                   1   

       having_At_Symbol  double_slash_redirecting  having_Sub_Domain  \
5033                  1                         1                 -1   
10307                -1                         1                  0   
7563                  1                         1                  0   
5911                  1                         1                  0   
9823                  1                         1                  1   
...                 ...                       ...                ...   
4859                  1                         1                  1   
3264                  1                         1                 -1   
9845                  1                         1                  1   
10799                 1                         1                 -1   
2732                  1                         1                  1   

       SSLfinal_State  Domain_registeration_length  Favicon  port  ...  \
5033                1                           -1        1     1  ...   
10307               0                           -1       -1    -1  ...   
7563                0                            1        1     1  ...   
5911               -1                            1        1     1  ...   
9823                1                           -1        1     1  ...   
...               ...                          ...      ...   ...  ...   
4859                1                           -1        1     1  ...   
3264               -1                            1        1     1  ...   
9845                1                           -1        1     1  ...   
10799               0                           -1        1     1  ...   
2732                1                           -1       -1    -1  ...   

       age_of_domain  DNSRecord  web_traffic  Page_Rank  Google_Index  \
5033               1         -1            1          1             1   
10307              1          1            0          1             1   
7563              -1          1           -1         -1             1   
5911              -1          1           -1         -1             1   
9823               1          1            1         -1             1   
...              ...        ...          ...        ...           ...   
4859               1         -1           -1         -1             1   
3264               1         -1            1         -1            -1   
9845               1          1            0          1             1   
10799              1          1            0         -1             1   
2732               1         -1            0         -1             1   

       Links_pointing_to_page  Statistical_report  Result  Prefix_Suffix_-1  \
5033                        1                   1       1                 0   
10307                       0                   1      -1                 1   
7563                        1                  -1      -1                 1   
5911                        0                   1      -1                 1   
9823                        0                  -1       1                 0   
...                       ...                 ...     ...               ...   
4859                        1                   1     

In [28]:
x_train.shape

(8844, 32)

In [29]:
x_test.shape

(2211, 32)

In [30]:
y_train.shape

(8844,)

In [31]:
y_test.shape

(2211,)

# Splitting The Data

In [36]:
#splitting data into independent and dependent variables
x,y = data.iloc[:,1:31].values,data.iloc[:,-1].values
print(x,y)

[[-1  1  1 ...  1  1 -1]
 [ 1  1  1 ...  1  1  1]
 [ 1  0  1 ...  1  0 -1]
 ...
 [ 1 -1  1 ...  1  0  1]
 [-1 -1  1 ...  1  1  1]
 [-1 -1  1 ... -1  1 -1]] [-1 -1 -1 ... -1 -1 -1]


In [38]:
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state = 42)
x_train.shape, y_train.shape, x_test.shape, y_test.shape

((8844, 30), (8844,), (2211, 30), (2211,))

# Creating a logistic regression model

In [39]:
# Creating holders to store the model performance results
ML_Model = []
accuracy = []
f1_score = []
recall = []
precision = []

#function to call for storing the results
def storeResults(model, a,b,c,d):
  ML_Model.append(model)
  accuracy.append(round(a, 3))
  f1_score.append(round(b, 3))
  recall.append(round(c, 3))
  precision.append(round(d, 3))

In [76]:
from sklearn.linear_model import LogisticRegression
lr=LogisticRegression()
lr.fit(x_train,y_train)

LogisticRegression()

In [77]:
y_train_lr = lr.predict(x_train)
y_test_lr = lr.predict(x_test)

In [78]:
acc_train_lr = metrics.accuracy_score(y_train,y_train_lr)
acc_test_lr = metrics.accuracy_score(y_test,y_test_lr)
print("Logistic Regression : Accuracy on training Data: {:.3f}".format(acc_train_lr))
print("Logistic Regression : Accuracy on test Data: {:.3f}".format(acc_test_lr))
print()

f1_score_train_lr = metrics.f1_score(y_train,y_train_lr)
f1_score_test_lr = metrics.f1_score(y_test,y_test_lr)
print("Logistic Regression : f1_score on training Data: {:.3f}".format(f1_score_train_lr))
print("Logistic Regression : f1_score on test Data: {:.3f}".format(f1_score_test_lr))
print()

recall_score_train_lr = metrics.recall_score(y_train,y_train_lr)
recall_score_test_lr = metrics.recall_score(y_test,y_test_lr)
print("Logistic Regression : Recall on training Data: {:.3f}".format(recall_score_train_lr))
print("Logistic Regression : Recall on test Data: {:.3f}".format(recall_score_test_lr))
print()

precision_score_train_lr = metrics.precision_score(y_train,y_train_lr)
precision_score_test_lr = metrics.precision_score(y_test,y_test_lr)
print("Logistic Regression : precision on training Data: {:.3f}".format(precision_score_train_lr))
print("Logistic Regression : precision on test Data: {:.3f}".format(precision_score_test_lr))

Logistic Regression : Accuracy on training Data: 0.929
Logistic Regression : Accuracy on test Data: 0.924

Logistic Regression : f1_score on training Data: 0.937
Logistic Regression : f1_score on test Data: 0.933

Logistic Regression : Recall on training Data: 0.947
Logistic Regression : Recall on test Data: 0.939

Logistic Regression : precision on training Data: 0.927
Logistic Regression : precision on test Data: 0.928


In [79]:
#computing the classification report of the model

print(metrics.classification_report(y_test, y_test_lr))

              precision    recall  f1-score   support

          -1       0.92      0.90      0.91       956
           1       0.93      0.94      0.93      1255

    accuracy                           0.92      2211
   macro avg       0.92      0.92      0.92      2211
weighted avg       0.92      0.92      0.92      2211



In [80]:
#storing the results. The below mentioned order of parameter passing is important.

storeResults('Logistic Regression',acc_test_lr,f1_score_test_lr,
             recall_score_train_lr,precision_score_train_lr)

In [81]:
ypred=lr.predict(x_test)
from sklearn.metrics import accuracy_score
log_reg=accuracy_score(y_test,ypred)
print(ypred,log_reg)

[-1 -1 -1 ... -1  1 -1] 0.9240162822252375


In [82]:
y_pred1=lr.predict(x_test)
from sklearn.metrics import accuracy_score
log_reg=accuracy_score(y_test,y_pred1)*100
log_reg

92.40162822252374

In [44]:
import pickle
pickle.dump(lr,open('Phishing_Website.pkl','wb'))

In [86]:
!pip install ibm_watson_machine_learning

In [87]:
from ibm_watson_machine_learning import APIClient
wml_credentials={
         "url":"https://us-south.ml.cloud.ibm.com",
         "apikey":"juc9T5KAkFdmG-PfwQcmwKNpafHTvq2xxn5KA8c5LBj2"
}
client=APIClient(wml_credentials)

In [88]:
def guid_from_space_name(client,space_name):
    space=client.spaces.get_details()
    #print(space) 
    return(next(item for item in space['resources']if item['entity']["name"]==space_name)['metadata']['id'])


In [89]:
space_uid=guid_from_space_name(client,'models')
print("Space UID = " + space_uid)

Space UID = 1a020fe3-6341-492a-8398-cf18b4b728ea


In [90]:
client.set.default_space(space_uid)

'SUCCESS'

In [91]:
client.software_specifications.list()

-----------------------------  ------------------------------------  ----
NAME                           ASSET_ID                              TYPE
default_py3.6                  0062b8c9-8b7d-44a0-a9b9-46c416adcbd9  base
kernel-spark3.2-scala2.12      020d69ce-7ac1-5e68-ac1a-31189867356a  base
pytorch-onnx_1.3-py3.7-edt     069ea134-3346-5748-b513-49120e15d288  base
scikit-learn_0.20-py3.6        09c5a1d0-9c1e-4473-a344-eb7b665ff687  base
spark-mllib_3.0-scala_2.12     09f4cff0-90a7-5899-b9ed-1ef348aebdee  base
pytorch-onnx_rt22.1-py3.9      0b848dd4-e681-5599-be41-b5f6fccc6471  base
ai-function_0.1-py3.6          0cdb0f1e-5376-4f4d-92dd-da3b69aa9bda  base
shiny-r3.6                     0e6e79df-875e-4f24-8ae9-62dcc2148306  base
tensorflow_2.4-py3.7-horovod   1092590a-307d-563d-9b62-4eb7d64b3f22  base
pytorch_1.1-py3.6              10ac12d6-6b30-4ccd-8392-3e922c096a92  base
tensorflow_1.15-py3.6-ddl      111e41b3-de2d-5422-a4d6-bf776828c4b7  base
autoai-kb_rt22.2-py3.10        125b6d9

In [92]:
MODEL_NAME = 'models'
DEPLOYMENT_LAYER = 'WebPhishingDetectionDeployment'
DEMO_MODEL = lr

In [93]:
software_spec_uid = client.software_specifications.get_id_by_name('runtime-22.1-py3.9')
software_spec_uid

'12b83a17-24d8-5082-900f-0ab31fbfd3cb'

In [94]:
model_props = {
    client.repository.ModelMetaNames.NAME: MODEL_NAME,
    client.repository.ModelMetaNames.TYPE: 'scikit-learn_1.0',
    client.repository.ModelMetaNames.SOFTWARE_SPEC_UID: software_spec_uid
}

In [95]:
#save model
model_details = client.repository.store_model(
    model=DEMO_MODEL,
    meta_props=model_props,
    training_data=x_train,
    training_target=y_train
)

In [96]:
model_details

{'entity': {'hybrid_pipeline_software_specs': [],
  'label_column': 'l1',
  'schemas': {'input': [{'fields': [{'name': 'f0', 'type': 'int'},
      {'name': 'f1', 'type': 'int'},
      {'name': 'f2', 'type': 'int'},
      {'name': 'f3', 'type': 'int'},
      {'name': 'f4', 'type': 'int'},
      {'name': 'f5', 'type': 'int'},
      {'name': 'f6', 'type': 'int'},
      {'name': 'f7', 'type': 'int'},
      {'name': 'f8', 'type': 'int'},
      {'name': 'f9', 'type': 'int'},
      {'name': 'f10', 'type': 'int'},
      {'name': 'f11', 'type': 'int'},
      {'name': 'f12', 'type': 'int'},
      {'name': 'f13', 'type': 'int'},
      {'name': 'f14', 'type': 'int'},
      {'name': 'f15', 'type': 'int'},
      {'name': 'f16', 'type': 'int'},
      {'name': 'f17', 'type': 'int'},
      {'name': 'f18', 'type': 'int'},
      {'name': 'f19', 'type': 'int'},
      {'name': 'f20', 'type': 'int'},
      {'name': 'f21', 'type': 'int'},
      {'name': 'f22', 'type': 'int'},
      {'name': 'f23', 'type': 'i

In [97]:
model_id = client.repository.get_model_id(model_details)
model_id

'6db5a9e5-48de-47dc-9fd4-4154847ce4b0'

In [98]:
x_train[0]

array([ 1, -1,  1,  1,  1, -1,  1,  1, -1,  1,  1,  1,  1,  1,  1, -1,  1,
        1,  0,  1,  1,  1,  1,  1,  1,  1, -1,  1,  0,  1])

In [99]:
x_train[0].reshape(1, -1)

array([[ 1, -1,  1,  1,  1, -1,  1,  1, -1,  1,  1,  1,  1,  1,  1, -1,
         1,  1,  0,  1,  1,  1,  1,  1,  1,  1, -1,  1,  0,  1]])

In [100]:
lr.predict([[ 1, -1,  1,  1,  1,  1, -1,  1, -1,  1,  1,  1,  1,  0, -1, -1,
         1,  1,  0,  1,  1,  1,  1,  1, -1,  1,  1,  1,  1,  1]])

array([1])