In [37]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [38]:

import os, types
import pandas as pd
from botocore.client import Config
import ibm_boto3

def __iter__(self): return 0

# @hidden_cell
# The following code accesses a file in your IBM Cloud Object Storage. It includes your credentials.
# You might want to remove those credentials before you share the notebook.
cos_client = ibm_boto3.client(service_name='s3',
    ibm_api_key_id='5R73qcy0t4mnMYG7VBnYKT8VLbRAXd0eOjK0enP7iwFz',
    ibm_auth_endpoint="https://iam.cloud.ibm.com/oidc/token",
    config=Config(signature_version='oauth'),
    endpoint_url='https://s3.private.us.cloud-object-storage.appdomain.cloud')

bucket = 'webphishingdetection-donotdelete-pr-fwpuuyxh90dcqj'
object_key = 'dataset_website.csv'

body = cos_client.get_object(Bucket=bucket,Key=object_key)['Body']
# add missing __iter__ method, so pandas accepts body as file-like object
if not hasattr(body, "__iter__"): body.__iter__ = types.MethodType( __iter__, body )

data = pd.read_csv(body)
data.head()


index  having_IPhaving_IP_Address  URLURL_Length  Shortining_Service  \
0      1                          -1              1                   1   
1      2                           1              1                   1   
2      3                           1              0                   1   
3      4                           1              0                   1   
4      5                           1              0                  -1   

   having_At_Symbol  double_slash_redirecting  Prefix_Suffix  \
0                 1                        -1             -1   
1                 1                         1             -1   
2                 1                         1             -1   
3                 1                         1             -1   
4                 1                         1             -1   

   having_Sub_Domain  SSLfinal_State  Domain_registeration_length  ...  \
0                 -1              -1                           -1  ...   
1                  0               1                           -1  ...   
2                 -1              -1                           -1  ...   
3                 -1              -1                            1  ...   
4                  1               1                           -1  ...   

   popUpWidnow  Iframe  age_of_domain  DNSRecord  web_traffic  Page_Rank  \
0            1       1             -1         -1           -1         -1   
1            1       1             -1         -1            0         -1   
2            1       1              1         -1            1         -1   
3            1       1             -1         -1            1         -1   
4           -1       1             -1         -1            0         -1   

   Google_Index  Links_pointing_to_page  Statistical_report  Result  
0             1                       1                  -1      -1  
1             1                       1                   1      -1  
2             1                       0                  -1      -1  
3             1                      -1                   1      -1  
4             1                       1                   1       1  

[5 rows x 32 columns]

In [39]:
type(data)

pandas.core.frame.DataFrame

In [40]:
data_main=pd.get_dummies(data,columns=['Prefix_Suffix'])
data_main

index  having_IPhaving_IP_Address  URLURL_Length  Shortining_Service  \
0          1                          -1              1                   1   
1          2                           1              1                   1   
2          3                           1              0                   1   
3          4                           1              0                   1   
4          5                           1              0                  -1   
...      ...                         ...            ...                 ...   
11050  11051                           1             -1                   1   
11051  11052                          -1              1                   1   
11052  11053                           1             -1                   1   
11053  11054                          -1             -1                   1   
11054  11055                          -1             -1                   1   

       having_At_Symbol  double_slash_redirecting  having_Sub_Domain  \
0                     1                        -1                 -1   
1                     1                         1                  0   
2                     1                         1                 -1   
3                     1                         1                 -1   
4                     1                         1                  1   
...                 ...                       ...                ...   
11050                -1                         1                  1   
11051                -1                        -1                  1   
11052                 1                         1                  1   
11053                 1                         1                 -1   
11054                 1                         1                 -1   

       SSLfinal_State  Domain_registeration_length  Favicon  ...  \
0                  -1                           -1        1  ...   
1                   1                           -1        1  ...   
2                  -1                           -1        1  ...   
3                  -1                            1        1  ...   
4                   1                           -1        1  ...   
...               ...                          ...      ...  ...   
11050               1                           -1       -1  ...   
11051              -1                           -1       -1  ...   
11052              -1                           -1        1  ...   
11053              -1                            1       -1  ...   
11054              -1                            1        1  ...   

       age_of_domain  DNSRecord  web_traffic  Page_Rank  Google_Index  \
0                 -1         -1           -1         -1             1   
1                 -1         -1            0         -1             1   
2                  1         -1            1         -1             1   
3                 -1         -1            1         -1             1   
4                 -1         -1            0         -1             1   
...              ...        ...          ...        ...           ...   
11050              1          1           -1         -1             1   
11051              1          1            1          1             1   
11052              1          1            1         -1             1   
11053              1          1            1         -1             1   
11054             -1          1           -1         -1            -1   

       Links_pointing_to_page  Statistical_report  Result  Prefix_Suffix_-1  \
0                           1                  -1      -1                 1   
1                           1                   1      -1                 1   
2                           0                  -1      -1                 1   
3                          -1                   1      -1                 1   
4                           1                   1       1                 1   
...                      

In [41]:

import os, types
import pandas as pd
from botocore.client import Config
import ibm_boto3

def __iter__(self): return 0

# @hidden_cell
# The following code accesses a file in your IBM Cloud Object Storage. It includes your credentials.
# You might want to remove those credentials before you share the notebook.
cos_client = ibm_boto3.client(service_name='s3',
    ibm_api_key_id='5R73qcy0t4mnMYG7VBnYKT8VLbRAXd0eOjK0enP7iwFz',
    ibm_auth_endpoint="https://iam.cloud.ibm.com/oidc/token",
    config=Config(signature_version='oauth'),
    endpoint_url='https://s3.private.us.cloud-object-storage.appdomain.cloud')

bucket = 'webphishingdetection-donotdelete-pr-fwpuuyxh90dcqj'
object_key = 'dataset_website.csv'

body = cos_client.get_object(Bucket=bucket,Key=object_key)['Body']
# add missing __iter__ method, so pandas accepts body as file-like object
if not hasattr(body, "__iter__"): body.__iter__ = types.MethodType( __iter__, body )

df_data_1 = pd.read_csv(body)
df_data_1.head()
y=data_main['URLURL_Length']
y.head()

0    1
1    1
2    0
3    0
4    0
Name: URLURL_Length, dtype: int64

In [42]:
x=data_main.drop(columns=['URLURL_Length'],axis=1)
x.head()

index  having_IPhaving_IP_Address  Shortining_Service  having_At_Symbol  \
0      1                          -1                   1                 1   
1      2                           1                   1                 1   
2      3                           1                   1                 1   
3      4                           1                   1                 1   
4      5                           1                  -1                 1   

   double_slash_redirecting  having_Sub_Domain  SSLfinal_State  \
0                        -1                 -1              -1   
1                         1                  0               1   
2                         1                 -1              -1   
3                         1                 -1              -1   
4                         1                  1               1   

   Domain_registeration_length  Favicon  port  ...  age_of_domain  DNSRecord  \
0                           -1        1     1  ...             -1         -1   
1                           -1        1     1  ...             -1         -1   
2                           -1        1     1  ...              1         -1   
3                            1        1     1  ...             -1         -1   
4                           -1        1     1  ...             -1         -1   

   web_traffic  Page_Rank  Google_Index  Links_pointing_to_page  \
0           -1         -1             1                       1   
1            0         -1             1                       1   
2            1         -1             1                       0   
3            1         -1             1                      -1   
4            0         -1             1                       1   

   Statistical_report  Result  Prefix_Suffix_-1  Prefix_Suffix_1  
0                  -1      -1                 1                0  
1                   1      -1                 1                0  
2                  -1      -1                 1                0  
3                   1      -1                 1                0  
4                   1       1                 1                0  

[5 rows x 32 columns]

In [43]:
from sklearn.model_selection import train_test_split

In [44]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=0)

In [45]:
x_train

index  having_IPhaving_IP_Address  Shortining_Service  \
5033    5034                           1                   1   
10307  10308                           1                   1   
7563    7564                          -1                   1   
5911    5912                           1                   1   
9823    9824                           1                   1   
...      ...                         ...                 ...   
4859    4860                           1                   1   
3264    3265                           1                   1   
9845    9846                          -1                   1   
10799  10800                          -1                   1   
2732    2733                           1                   1   

       having_At_Symbol  double_slash_redirecting  having_Sub_Domain  \
5033                  1                         1                 -1   
10307                -1                         1                  0   
7563                  1                         1                  0   
5911                  1                         1                  0   
9823                  1                         1                  1   
...                 ...                       ...                ...   
4859                  1                         1                  1   
3264                  1                         1                 -1   
9845                  1                         1                  1   
10799                 1                         1                 -1   
2732                  1                         1                  1   

       SSLfinal_State  Domain_registeration_length  Favicon  port  ...  \
5033                1                           -1        1     1  ...   
10307               0                           -1       -1    -1  ...   
7563                0                            1        1     1  ...   
5911               -1                            1        1     1  ...   
9823                1                           -1        1     1  ...   
...               ...                          ...      ...   ...  ...   
4859                1                           -1        1     1  ...   
3264               -1                            1        1     1  ...   
9845                1                           -1        1     1  ...   
10799               0                           -1        1     1  ...   
2732                1                           -1       -1    -1  ...   

       age_of_domain  DNSRecord  web_traffic  Page_Rank  Google_Index  \
5033               1         -1            1          1             1   
10307              1          1            0          1             1   
7563              -1          1           -1         -1             1   
5911              -1          1           -1         -1             1   
9823               1          1            1         -1             1   
...              ...        ...          ...        ...           ...   
4859               1         -1           -1         -1             1   
3264               1         -1            1         -1            -1   
9845               1          1            0          1             1   
10799              1          1            0         -1             1   
2732               1         -1            0         -1             1   

       Links_pointing_to_page  Statistical_report  Result  Prefix_Suffix_-1  \
5033                        1                   1       1                 0   
10307                       0                   1      -1                 1   
7563                        1                  -1      -1                 1   
5911                        0                   1      -1                 1   
9823                        0                  -1       1                 0   
...                       ...                 ...     ...               ...   
4859                        1                   1     

In [46]:
x_train.shape

(8844, 32)

In [47]:
x_test.shape

(2211, 32)

In [48]:
y_train.shape

(8844,)

In [49]:
y_test.shape

(2211,)

In [50]:
#splitting data into independent and dependent variables
x,y = data.iloc[:,1:31].values,data.iloc[:,-1].values
print(x,y)

[[-1  1  1 ...  1  1 -1]
 [ 1  1  1 ...  1  1  1]
 [ 1  0  1 ...  1  0 -1]
 ...
 [ 1 -1  1 ...  1  0  1]
 [-1 -1  1 ...  1  1  1]
 [-1 -1  1 ... -1  1 -1]] [-1 -1 -1 ... -1 -1 -1]


# Creating a logistic regression model

In [51]:
from sklearn.linear_model import LogisticRegression
lr=LogisticRegression()
lr.fit(x_train,y_train)

/opt/conda/envs/Python-3.9/lib/python3.9/site-packages/sklearn/linear_model/_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [52]:
ypred=lr.predict(x_test)
from sklearn.metrics import accuracy_score
log_reg=accuracy_score(y_test,ypred)
print(ypred,log_reg)

[-1 -1 -1 ... -1 -1 -1] 0.8647670737222976


In [53]:
import pickle
pickle.dump(lr,open('Phishing_Website.pkl','wb'))